{"variants":[{"paths":["\/documentation\/surfplaybook"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/surfplaybook"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/ru.surfstudio.playbook.SurfPlaybook\/documentation\/SurfPlaybook","interfaceLanguage":"swift"},"topicSections":[{"title":"Classes","identifiers":["doc:\/\/ru.surfstudio.playbook.SurfPlaybook\/documentation\/SurfPlaybook\/Playbook","doc:\/\/ru.surfstudio.playbook.SurfPlaybook\/documentation\/SurfPlaybook\/PlaybookChapter","doc:\/\/ru.surfstudio.playbook.SurfPlaybook\/documentation\/SurfPlaybook\/TableViewCellContainer","doc:\/\/ru.surfstudio.playbook.SurfPlaybook\/documentation\/SurfPlaybook\/ViewContainer"]},{"title":"Protocols","identifiers":["doc:\/\/ru.surfstudio.playbook.SurfPlaybook\/documentation\/SurfPlaybook\/PlaybookCellConfigurable","doc:\/\/ru.surfstudio.playbook.SurfPlaybook\/documentation\/SurfPlaybook\/PlaybookFlowCoordinator","doc:\/\/ru.surfstudio.playbook.SurfPlaybook\/documentation\/SurfPlaybook\/PlaybookUIKitPage","doc:\/\/ru.surfstudio.playbook.SurfPlaybook\/documentation\/SurfPlaybook\/StringRepresentable","doc:\/\/ru.surfstudio.playbook.SurfPlaybook\/documentation\/SurfPlaybook\/UIKitPageViewModel"]},{"title":"Structures","identifiers":["doc:\/\/ru.surfstudio.playbook.SurfPlaybook\/documentation\/SurfPlaybook\/PlaybookPage"]},{"title":"Enumerations","identifiers":["doc:\/\/ru.surfstudio.playbook.SurfPlaybook\/documentation\/SurfPlaybook\/ColorsConfig","doc:\/\/ru.surfstudio.playbook.SurfPlaybook\/documentation\/SurfPlaybook\/FlowCoordinatorType","doc:\/\/ru.surfstudio.playbook.SurfPlaybook\/documentation\/SurfPlaybook\/StringsConfig"]}],"kind":"symbol","metadata":{"roleHeading":"Framework","externalID":"SurfPlaybook","title":"SurfPlaybook","symbolKind":"module","role":"collection","modules":[{"name":"SurfPlaybook"}]},"hierarchy":{"paths":[[]]},"references":{"doc://ru.surfstudio.playbook.SurfPlaybook/documentation/SurfPlaybook/PlaybookFlowCoordinator":{"role":"symbol","title":"PlaybookFlowCoordinator","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlaybookFlowCoordinator"}],"abstract":[{"type":"text","text":"В плейбуке присутствует возможность показа какого либо экрана приложения,"},{"type":"text","text":" "},{"type":"text","text":"либо запуска целого flow приложения."},{"type":"text","text":" "},{"type":"text","text":"Данный протокол предназначен для объектов, способных это сделать."}],"identifier":"doc:\/\/ru.surfstudio.playbook.SurfPlaybook\/documentation\/SurfPlaybook\/PlaybookFlowCoordinator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PlaybookFlowCoordinator"}],"url":"\/documentation\/surfplaybook\/playbookflowcoordinator"},"doc://ru.surfstudio.playbook.SurfPlaybook/documentation/SurfPlaybook/PlaybookChapter":{"role":"symbol","title":"PlaybookChapter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlaybookChapter"}],"abstract":[{"type":"text","text":"Отдельная глава Playbook-а."}],"identifier":"doc:\/\/ru.surfstudio.playbook.SurfPlaybook\/documentation\/SurfPlaybook\/PlaybookChapter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PlaybookChapter"}],"url":"\/documentation\/surfplaybook\/playbookchapter"},"doc://ru.surfstudio.playbook.SurfPlaybook/documentation/SurfPlaybook/SurfPlaybookVersionNumber":{"role":"symbol","title":"SurfPlaybookVersionNumber","fragments":[{"kind":"identifier","text":"SurfPlaybookVersionNumber"}],"abstract":[{"type":"text","text":"Project version number for SurfPlaybook."}],"identifier":"doc:\/\/ru.surfstudio.playbook.SurfPlaybook\/documentation\/SurfPlaybook\/SurfPlaybookVersionNumber","kind":"symbol","type":"topic","url":"\/documentation\/surfplaybook\/surfplaybookversionnumber"},"doc://ru.surfstudio.playbook.SurfPlaybook/documentation/SurfPlaybook/Playbook":{"role":"symbol","title":"Playbook","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Playbook"}],"abstract":[{"type":"text","text":"Основной класс для всей механики playbook-а."}],"identifier":"doc:\/\/ru.surfstudio.playbook.SurfPlaybook\/documentation\/SurfPlaybook\/Playbook","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Playbook"}],"url":"\/documentation\/surfplaybook\/playbook"},"doc://ru.surfstudio.playbook.SurfPlaybook/documentation/SurfPlaybook/UIKitPageViewModel":{"role":"symbol","title":"UIKitPageViewModel","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIKitPageViewModel"}],"abstract":[{"type":"text","text":"Протокол для объекта, способного построить табличный экран"},{"type":"text","text":" "},{"type":"text","text":"для показа страницы UIKit-а"}],"identifier":"doc:\/\/ru.surfstudio.playbook.SurfPlaybook\/documentation\/SurfPlaybook\/UIKitPageViewModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UIKitPageViewModel"}],"url":"\/documentation\/surfplaybook\/uikitpageviewmodel"},"doc://ru.surfstudio.playbook.SurfPlaybook/documentation/SurfPlaybook/StringsConfig":{"role":"symbol","title":"StringsConfig","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"StringsConfig"}],"abstract":[{"type":"text","text":"Используемые тексты внутри playbook-а"}],"identifier":"doc:\/\/ru.surfstudio.playbook.SurfPlaybook\/documentation\/SurfPlaybook\/StringsConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StringsConfig"}],"url":"\/documentation\/surfplaybook\/stringsconfig"},"doc://ru.surfstudio.playbook.SurfPlaybook/documentation/SurfPlaybook/ViewContainer":{"role":"symbol","title":"ViewContainer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ViewContainer"}],"abstract":[{"type":"text","text":"Вспомогательный контейнер-view, позвооляет обернуть UI-компонент типа UIView"},{"type":"text","text":" "},{"type":"text","text":"в таблицу, чтобы показать его в рамках playbook-а."}],"identifier":"doc:\/\/ru.surfstudio.playbook.SurfPlaybook\/documentation\/SurfPlaybook\/ViewContainer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ViewContainer"}],"url":"\/documentation\/surfplaybook\/viewcontainer"},"doc://ru.surfstudio.playbook.SurfPlaybook/documentation/SurfPlaybook/StringRepresentable":{"role":"symbol","title":"StringRepresentable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"StringRepresentable"}],"abstract":[{"type":"text","text":"Абстрактный протокол для всех возможных вариантов выбора внутри модуля OptionSelector."},{"type":"text","text":" "},{"type":"text","text":"Обязательное условие - объект должен иметь строковое представление, которое будет отображаться в UI."}],"identifier":"doc:\/\/ru.surfstudio.playbook.SurfPlaybook\/documentation\/SurfPlaybook\/StringRepresentable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"StringRepresentable"}],"url":"\/documentation\/surfplaybook\/stringrepresentable"},"doc://ru.surfstudio.playbook.SurfPlaybook/documentation/SurfPlaybook/PlaybookUIKitPage":{"role":"symbol","title":"PlaybookUIKitPage","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlaybookUIKitPage"}],"abstract":[{"type":"text","text":"Протокол, который должна реализовывать каждая страница UIKIt-а в рамках playbook-а."}],"identifier":"doc:\/\/ru.surfstudio.playbook.SurfPlaybook\/documentation\/SurfPlaybook\/PlaybookUIKitPage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PlaybookUIKitPage"}],"url":"\/documentation\/surfplaybook\/playbookuikitpage"},"doc://ru.surfstudio.playbook.SurfPlaybook/documentation/SurfPlaybook/TableViewCellContainer":{"role":"symbol","title":"TableViewCellContainer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TableViewCellContainer"}],"abstract":[{"type":"text","text":"Вспомогательный контейнер-таблица, позвооляет обернуть UI-компонент типа UITableViewCell"},{"type":"text","text":" "},{"type":"text","text":"в таблицу, чтобы показать его в рамках playbook-а."}],"identifier":"doc:\/\/ru.surfstudio.playbook.SurfPlaybook\/documentation\/SurfPlaybook\/TableViewCellContainer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TableViewCellContainer"}],"url":"\/documentation\/surfplaybook\/tableviewcellcontainer"},"doc://ru.surfstudio.playbook.SurfPlaybook/documentation/SurfPlaybook/PlaybookPage":{"role":"symbol","title":"PlaybookPage","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlaybookPage"}],"abstract":[{"type":"text","text":"Отдельная страница playbook-а."}],"identifier":"doc:\/\/ru.surfstudio.playbook.SurfPlaybook\/documentation\/SurfPlaybook\/PlaybookPage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PlaybookPage"}],"url":"\/documentation\/surfplaybook\/playbookpage"},"doc://ru.surfstudio.playbook.SurfPlaybook/documentation/SurfPlaybook/ColorsConfig":{"role":"symbol","title":"ColorsConfig","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ColorsConfig"}],"abstract":[{"type":"text","text":"Конфиг со всеми цветами приложения."}],"identifier":"doc:\/\/ru.surfstudio.playbook.SurfPlaybook\/documentation\/SurfPlaybook\/ColorsConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ColorsConfig"}],"url":"\/documentation\/surfplaybook\/colorsconfig"},"doc://ru.surfstudio.playbook.SurfPlaybook/documentation/SurfPlaybook/PlaybookCellConfigurable":{"role":"symbol","title":"PlaybookCellConfigurable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlaybookCellConfigurable"}],"abstract":[{"type":"text","text":"В случае, если ячейка находится в SPM-пакете,"},{"type":"text","text":" "},{"type":"text","text":"необходимо подписать ее под протокол и указать Bundle.module"}],"identifier":"doc:\/\/ru.surfstudio.playbook.SurfPlaybook\/documentation\/SurfPlaybook\/PlaybookCellConfigurable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PlaybookCellConfigurable"}],"url":"\/documentation\/surfplaybook\/playbookcellconfigurable"},"doc://ru.surfstudio.playbook.SurfPlaybook/documentation/SurfPlaybook/FlowCoordinatorType":{"role":"symbol","title":"FlowCoordinatorType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FlowCoordinatorType"}],"abstract":[{"type":"text","text":"Тип flow-координатора"}],"identifier":"doc:\/\/ru.surfstudio.playbook.SurfPlaybook\/documentation\/SurfPlaybook\/FlowCoordinatorType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FlowCoordinatorType"}],"url":"\/documentation\/surfplaybook\/flowcoordinatortype"},"doc://ru.surfstudio.playbook.SurfPlaybook/documentation/SurfPlaybook/SurfPlaybookVersionString":{"role":"symbol","title":"SurfPlaybookVersionString","fragments":[{"kind":"identifier","text":"SurfPlaybookVersionString"}],"abstract":[{"type":"text","text":"Project version string for SurfPlaybook."}],"identifier":"doc:\/\/ru.surfstudio.playbook.SurfPlaybook\/documentation\/SurfPlaybook\/SurfPlaybookVersionString","kind":"symbol","type":"topic","url":"\/documentation\/surfplaybook\/surfplaybookversionstring"},"doc://ru.surfstudio.playbook.SurfPlaybook/documentation/SurfPlaybook":{"role":"collection","title":"SurfPlaybook","abstract":[],"identifier":"doc:\/\/ru.surfstudio.playbook.SurfPlaybook\/documentation\/SurfPlaybook","kind":"symbol","type":"topic","url":"\/documentation\/surfplaybook"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Variables","identifiers":["doc:\/\/ru.surfstudio.playbook.SurfPlaybook\/documentation\/SurfPlaybook\/SurfPlaybookVersionNumber","doc:\/\/ru.surfstudio.playbook.SurfPlaybook\/documentation\/SurfPlaybook\/SurfPlaybookVersionString"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null}],"traits":[{"interfaceLanguage":"occ"}]}]}