name: CI

# Controls when the action will run. 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'
    types: [ opened, edited, synchronize ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: CocoaPods
      run: |
        gem install xcpretty -N
        make init
    - name: Build
      run: |
        make build
    - name: SPM Build
      run: |
        make spm_build
    - name: Example Build
      run: |
        make example_build
